version: '3.9'
services:
  app:
    build: .
    container_name: drive-nest-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: drive-nest-db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
